### ISSUE TITLE
How do I create a completely random/fake object with its properties set by factory_boy?

### ISSUE THREAD

**Issue by JobaDiniz** [FactoryBoy/factory_boy#1084] opened 2024-08-01 20:31 UTC
#### The problem
I have a _pydantic_ model which has several fields. I want to generate instances of this model for testing. But I don't care about the values of the fields. I do care that they are set with something. Since there's a lot to set, manually setting this is hard and cumbersome. I don't test specific attributes in the test. I will pass these instances to a _system under test_ (function) and the result will be assert.

#### Proposed solution
```
class InterestingElement(BaseModel):
    id: str
    html: Html
    match: Match
    selectors: ElementSelector
    text: Text
    nearbyLabels: list["InterestingElement"]

class InterestingElementFactory(factory.Factory):
    class Meta:
        model = InterestingElement

instance_with_everything_set_with_faker_by_default = InterestingElementFactory.build()
```

**Comment by francoisfreitag** [comment] 2024-08-05 07:21
Looks like a duplicate of https://github.com/FactoryBoy/factory_boy/issues/836

**Closed by francoisfreitag** 2024-08-05 07:21 UTC
