### ISSUE TITLE
save() method called twice when using post_generation

### ISSUE THREAD

**Issue by romgar** [FactoryBoy/factory_boy#316] opened 2016-07-29 09:34 UTC
I just realised that my model factory was calling the model `save` method twice when defining `post_generation` function. Here is the many-to-many example:

``` python
class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = models.User

    name = "John Doe"

    @factory.post_generation
    def groups(self, create, extracted, **kwargs):
        if not create:
            # Simple build, do nothing.
            return

        if extracted:
            # A list of groups were passed in, use them
            for group in extracted:
                self.groups.add(group)
```

Calling `UserFactory` triggers `save()` on `User` model twice.

This happens because:
1/ The `DjangoModelFactory` redefines `_after_postgeneration`:

``` python
    @classmethod
    def _after_postgeneration(cls, obj, create, results=None):
        """Save again the instance if creating and at least one hook ran."""
        if create and results:
            # Some post-generation hooks ran, and may have modified us.
            obj.save()
```

2/ This `results` comes from the call to our post_generation function, which with previous `User` example returns `{'groups': None}`

Which use case has led to this post-generation saving? If some data had to be saved in a custom `post_generation` function, nothing is preventing to explicitly call `save` on `obj`.

Do I have missed something?
Should I override this method if I don't want to get this double `save()` on my model, or there is a better way?

**Comment by grutts** [comment] 2016-08-04 16:27
I had this problem as well, spotted it when one of my tests was behaving unexpectedly. I overrode _after_postgeneration to do nothing

**Comment by rbarrois** [comment] 2016-08-06 10:00
This is useful for declarations such as:

```python
class UserFactory(factory.Factory):
    class Meta:
        model = User

    username = factory.Faker('username')
    password = factory.PostGenerationMethodCall('set_password', 'Password123')
```

In such cases, we want to have the factory be saved again after the call to ``set_password``.

What kinds of problems are caused by this double ``save()``?

**Comment by romgar** [comment] 2016-08-10 13:49
It really depends on what you define in your `save()` method, but you could imagine anything: trigger to sync some data to an external API, update other fields, ...
Maybe a parameter to explicitly save in this post generation environment would be a lead to solve this, but I'm not convinced that's something `factory_boy` should do by default (a warning could also be added in the documentation).

**Comment by mlorant** [comment] 2016-11-09 09:11
@rbarrois Have the same problem this morning. Calling the `save()` twice is problematic if your model tries to keep a date of last update. For example:

```
class TimeStampedModel(models.Model):
    """ ... """
    creation_date = models.DateTimeField(_("date de création"), default=timezone.now)
    update_date = models.DateTimeField(_("date de mise à jour"), null=True, blank=True)
    created_by = ...
    updated_by = ...

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if self.pk:
            self.update_date = timezone.now()

        super().save(*args, **kwargs)
```

A model that is going to call `save()` twice will set `update_date` to something near `creation_date` (but not exactly the same), while the expected result is of course `update_date` to be `None`. 

A workaround would be to replace `results` by `any(results.values())` in the condition check of `_after_postgeneration`, or this can have side-effect on related set creation?

**Comment by rbarrois** [comment] 2016-11-10 14:16
@mlorant I agree that this is getting closer to a bug than to a feature.

The only problem I have right now is that this behavior is used in the documentation: http://factoryboy.readthedocs.io/en/latest/reference.html#postgenerationmethodcall

Does any participant to this issue have a suggestion for a better example, and a fix for this Django-side method (i.e "how do I pass a salted password to the User factory?") to add to the recipes section?

Once that is done, I'll be happy to merge the fix for this bug ;)

**Comment by romgar** [comment] 2016-11-10 14:58
I don't think the `PostGenerationMethodCall` is a nice shortcut at the end. And it's a bit against one of the Zen motto `There should be one-- and preferably only one --obvious way to do it`.

`PostGeneration` is already enough, and introducing this double save to allow this `PostGenerationMethodCall` is imho not a great idea.

Deprecating it? :-)

**Comment by rbarrois** [comment] 2017-04-07 15:29
Yep, the goal is that once #366 is closed, we should have much less use for the post-generation save (or make it explicit, with... ``PostGenerationMethodCall('save')`` :wink:

**Closed** 2021-02-12 22:17 UTC
Labels: Django

**Comment by michalpleszczynski** [comment] 2023-10-02 10:55
For anybody that stumbles upon this before 4.0 is released, the way to skip the extra save is:
```
class MyFactory(DjangoModelFactory):
  class Meta:
     skip_postgeneration_save = True
```
