### ISSUE TITLE
New version of factory_boy does not work with a simple RelatedFactory case

### ISSUE THREAD

**Issue by domino14** [FactoryBoy/factory_boy#402] opened 2017-08-04 01:08 UTC
Hi all, I upgraded to factory_boy 2.9.1 and a bunch of my tests are failing. I've isolated it down to a simple set of models. This was modeled on the documentation.

```python
import factory

from django.db import models
from django.contrib.auth.models import User

from base.models import Account, Profile


class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = User

    # We pass in 'user' to link the generated Profile to our just-generated
    # User. This will call ProfileFactory(user=our_new_user), thus
    # skipping the SubFactory.
    profile = factory.RelatedFactory(
        'base.tests.factories.broken_factories.ProfileFactory', 'user')
    username = factory.Sequence(lambda n: 'user.username%d' % n)


class AccountFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Account

    admin = factory.SubFactory(UserFactory)
    name = factory.SelfAttribute('admin.email')


class ProfileFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Profile

    # We pass in None to prevent UserFactory from creating another
    # profile (this disables the RelatedFactory)
    user = factory.SubFactory(UserFactory, profile=None)

```

In my `base.models`, `Account` and `Profile` look like this, roughly:

```python
class Account(models.Model):
    admin = models.ForeignKey(User, related_name='account_admin')
    name = models.CharField(max_length=64)


class Profile(models.Model):
    user = models.OneToOneField(User)
```

This fails in my tests when I instantiate `AccountFactory()` with no arguments. This is the error traceback and messaging:

```
DEBUG 2017-08-03 18:03:29,012 [factory.generate] [declarations.py::generate:392 ] SubFactory: Instantiating base.tests.factories.broken_factories.UserFactory(), create=<factory.builder.BuildStep object at 0x7faf4ef4bf50>
DEBUG 2017-08-03 18:03:29,012 [factory.generate] [declarations.py::evaluate:206 ] Sequence: Computing next value of <function <lambda> at 0x7faf54f447d0> for seq=0
DEBUG 2017-08-03 18:03:29,015 [factory.generate] [declarations.py::call:615 ] RelatedFactory: Generating base.tests.factories.broken_factories.ProfileFactory(<factory.builder.BuildStep object at 0x7faf4f9e3110>, user=<User: user.username0>)
DEBUG 2017-08-03 18:03:29,015 [factory.generate] [declarations.py::evaluate:58 ] LazyFunction: Evaluating <built-in function time> on <factory.builder.BuildStep object at 0x7faf4f76b410>
E
======================================================================
ERROR: test_broken_factory (base.tests.test_factories.FactoryTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/djapp/base/tests/test_factories.py", line 51, in test_broken_factory
    AccountFactory()
  File "/usr/local/lib/python2.7/site-packages/factory/base.py", line 46, in __call__
    return cls.create(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/factory/base.py", line 568, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/usr/local/lib/python2.7/site-packages/factory/base.py", line 505, in _generate
    return step.build()
  File "/usr/local/lib/python2.7/site-packages/factory/builder.py", line 272, in build
    step.resolve(pre)
  File "/usr/local/lib/python2.7/site-packages/factory/builder.py", line 221, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/usr/local/lib/python2.7/site-packages/factory/builder.py", line 363, in __getattr__
    extra=declaration.context,
  File "/usr/local/lib/python2.7/site-packages/factory/declarations.py", line 306, in evaluate
    return self.generate(step, defaults)
  File "/usr/local/lib/python2.7/site-packages/factory/declarations.py", line 395, in generate
    return step.recurse(subfactory, params, force_sequence=force_sequence)
  File "/usr/local/lib/python2.7/site-packages/factory/builder.py", line 233, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
  File "/usr/local/lib/python2.7/site-packages/factory/builder.py", line 293, in build
    context=postgen_context,
  File "/usr/local/lib/python2.7/site-packages/factory/declarations.py", line 617, in call
    return step.recurse(factory, passed_kwargs)
  File "/usr/local/lib/python2.7/site-packages/factory/builder.py", line 233, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
  File "/usr/local/lib/python2.7/site-packages/factory/builder.py", line 279, in build
    kwargs=kwargs,
  File "/usr/local/lib/python2.7/site-packages/factory/base.py", line 314, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/factory/django.py", line 165, in _create
    return manager.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1062, "Duplicate entry '1' for key 'user_id'")
```

**Comment by jeffwidman** [comment] 2017-08-04 18:29
It sounds like a previous version of FactoryBoy was working with this code... what version was that? 

Any idea which version broke your code?

**Comment by domino14** [comment] 2017-08-04 19:56
2.8.1 worked, and 2.9/2.9.1 don't work with my code.

**Comment by rbarrois** [comment] 2017-08-04 23:07
@domino14 I've tried to reproduce the issue, but it's all working so far.

Could you take a look at the testcase in the attached branch and try to get them closer to your setup to reproduce the failure?

Thanks!

**Comment by domino14** [comment] 2017-08-07 22:18
I'll try to do this soon. In the meantime, it seems the only difference is that my `UserFactory` model overrides the `_generate_` function:

```python
    @classmethod
    def _generate(cls, create, attrs):
        """Override the default _generate() to disable the post-save signal."""

        post_save.disconnect(generate_profile, User)
        user = super(UserFactory, cls)._generate(create, attrs)
        post_save.connect(generate_profile, User)
        return user
```

`generate_profile` is a function that generates a `Profile` for the user. I have a feeling that based on the error, this signal handler is not being disconnected properly anymore, so we're trying to generate duplicate `Profile`s. Does the `_generate` override still work as expected in 2.9?

**Comment by rbarrois** [comment] 2017-08-16 14:39
OK, this is the reason: the ``_generate`` function was a private method, and has been removed in 2.9.0.

To be fair, it is listed in the ``recipes()`` section, so the problem is on our side; we should send a warning if a ``_generate()`` method is detected on a factory definition.

Have you taken a look at the [``factory.django.mute_signals``](https://factoryboy.readthedocs.io/en/latest/orms.html#disabling-signals) helper?

**Comment by jeffwidman** [comment] 2017-08-16 18:10
I'm tempted to close this, as `_generate()` is clearly delineated as private due to the `_` prefix.

>we should send a warning if a _generate() method is detected on a factory definition.

I know a few folks may hit problems during their migration to 2.9, but I don't think it's worth the effort to add this code, especially since it's only temporarily needed and then will become cruft that needs to be removed...

**Comment by domino14** [comment] 2017-08-16 21:48
This is still broken for me, after adding the `mute_signals` helper. Can the docs be updated to show how to use it? My example came directly from the recipes.

Is this still the same? What is the recommended way of doing what I want to do (prevent the creation via signalhandlers of a related model)?
```python
    # We pass in None to prevent UserFactory from creating another
    # profile (this disables the RelatedFactory)
    user = factory.SubFactory(UserFactory, profile=None)
```

**Comment by EmilStenstrom** [comment] 2017-08-25 11:35
I got test failures because of this even in factory-boy 2.8.1. I had a factory with an overridden _generate method, and it wasn't called when Django was upgrade to 1.11.

**Comment by rbarrois** [comment] 2017-08-28 19:50
@domino14 do you have an example code snippet and stack trace I could look into?

@EmilStenstrom if your problem was already there in 2.8.1, then it might be something else altogether; do you have a stacktrace and an example code snippet?

**Comment by wdoekes** [comment] 2017-09-06 16:10
I just spent too much time debugging a problem that started between 2.8.1 and 2.9.2, and it finally turned out to be a missing mute_signals (like mentioned above).

In my case, I had UserFactory and ContactFactory which both instantiated each other. The former factory had a mute_signals, but the latter had not. The ContactFactory caused a User to get created which caused the post_save signals to create a Contact, which removed the need to create any further contact: this appeared to me as factoryboy ignoring my arguments to the ContactFactory.

Glad to get that sorted.

**Comment by rbarrois** [comment] 2018-01-28 22:01
I'm closing this issue for now, since it seems to be due to an internals refactor messing up with an private-yet-slightly-documented method.

Please reopen it if the bug is still out there, or if the documentation fixes aren't sufficient!

**Closed by rbarrois** 2018-01-28 22:01 UTC
Labels: Django, Doc, NeedInfo
