### ISSUE TITLE
Installation fails depending on locale

### ISSUE THREAD

**Issue by choeger** [FactoryBoy/factory_boy#770] opened 2020-08-13 07:30 UTC
A CI system just failed when installing factory_boy while I could install it locally. Turns out the locale makes a difference:

```
(venv) ➜  /tmp LC_ALL=C pip install --force factory_boy
Collecting factory_boy
  Using cached https://files.pythonhosted.org/packages/e4/ca/ad899f91979352aa06b9a35b5ca436adfa9782924832a02fdbb6fce1c075/factory_boy-3.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uo6r_saz/factory-boy/setup.py", line 5, in <module>
        setup()
      File "/tmp/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/tmp/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 135, in _install_setup_requires
        dist.parse_config_files(ignore_option_errors=True)
      File "/tmp/venv/lib/python3.6/site-packages/setuptools/dist.py", line 564, in parse_config_files
        _Distribution.parse_config_files(self, filenames=filenames)
      File "/opt/c1/lib/python3.6/distutils/dist.py", line 395, in parse_config_files
        parser.read(filename)
      File "/opt/c1/lib/python3.6/configparser.py", line 697, in read
        self._read(fp, filename)
      File "/opt/c1/lib/python3.6/configparser.py", line 1015, in _read
        for lineno, line in enumerate(fp, start=1):
      File "/opt/c1/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 261: ordinal not in range(128)
```

**Comment by rbarrois** [comment] 2020-08-13 08:01
This is intriguing; looks like setuptools/configparser don't specify an encoding when opening the file.
Can you try setting [PYTHONIOENCODING](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING)?

**Comment by choeger** [comment] 2020-08-13 08:11
```
(venv) ➜  /tmp PYTHONIOENCODING=UTF-8 pip install --force factory_boy
Collecting factory_boy
  Downloading https://files.pythonhosted.org/packages/9f/ae/a9120831abb254db2bd9381bbda81323e8265ba2a2a8bfdccf941fb39362/factory_boy-3.0.1.tar.gz (155kB)
    100% |████████████████████████████████| 163kB 141kB/s 
Collecting Faker>=0.7.0 (from factory_boy)
  Using cached https://files.pythonhosted.org/packages/de/21/a0c2ed68ca140d0a5bd0ac762f05cbe03dd52ffb577ae5d5c973dc85e103/Faker-4.1.1-py3-none-any.whl
Collecting python-dateutil>=2.4 (from Faker>=0.7.0->factory_boy)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting text-unidecode==1.3 (from Faker>=0.7.0->factory_boy)
  Using cached https://files.pythonhosted.org/packages/a6/a5/c0b6468d3824fe3fde30dbb5e1f687b291608f9473681bbf7dabbf5a87d7/text_unidecode-1.3-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.4->Faker>=0.7.0->factory_boy)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, text-unidecode, Faker, factory-boy
  Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Found existing installation: python-dateutil 2.8.1
    Uninstalling python-dateutil-2.8.1:
      Successfully uninstalled python-dateutil-2.8.1
  Found existing installation: text-unidecode 1.3
    Uninstalling text-unidecode-1.3:
      Successfully uninstalled text-unidecode-1.3
  Found existing installation: Faker 4.1.1
    Uninstalling Faker-4.1.1:
      Successfully uninstalled Faker-4.1.1
  Found existing installation: factory-boy 3.0.0
    Uninstalling factory-boy-3.0.0:
      Successfully uninstalled factory-boy-3.0.0
  Running setup.py install for factory-boy ... done
Successfully installed Faker-4.1.1 factory-boy-3.0.1 python-dateutil-2.8.1 six-1.15.0 text-unidecode-1.3
```

**Comment by rbarrois** [comment] 2020-08-13 08:26
Good, that's at least a hint of a possible solution. I fail to reproduce the issue locally (in a shell), did you manage to reproduce the breakage locally?

**Comment by rbarrois** [comment] 2020-08-13 08:33
I've tried under docker, with `docker run --rm -ti --env LC_ALL=C --env LANG=C python pip install factory_boy`

But the installation succeeds seamlessly:

```
Collecting factory_boy
  Downloading factory_boy-3.0.1.tar.gz (155 kB)
     |████████████████████████████████| 155 kB 5.0 MB/s 
Collecting Faker>=0.7.0
  Downloading Faker-4.1.1-py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 8.1 MB/s 
Collecting python-dateutil>=2.4
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 9.3 MB/s 
Collecting text-unidecode==1.3
  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 6.9 MB/s 
Collecting six>=1.5
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: factory-boy
  Building wheel for factory-boy (setup.py) ... done
  Created wheel for factory-boy: filename=factory_boy-3.0.1-py3-none-any.whl size=35615 sha256=a668b3a49a8f2e3947335d52c1d5b11ece31871a5b95ce2e72908a0e665f45fa
  Stored in directory: /root/.cache/pip/wheels/46/44/7a/777931e1ec2d305e433232f7fe7c28f152a651e82d5b876836
Successfully built factory-boy
Installing collected packages: six, python-dateutil, text-unidecode, Faker, factory-boy
Successfully installed Faker-4.1.1 factory-boy-3.0.1 python-dateutil-2.8.1 six-1.15.0 text-unidecode-1.3
```

**Comment by choeger** [comment] 2020-08-13 08:55
I just checked with a different interpreter and that worked. So the root cause is probably baked inside our python interpreter's configuration. Still, your latest upgrade broke the build for the first time. Do you have any idea what could have changed with factory_boy's dependencies in 3.0.0 ?

**Comment by rbarrois** [comment] 2020-08-13 19:23
We changed the way setuptools is configured, moving all the metadata to `setup.cfg.

Since parts of the metadata contains non-ASCII characters, if your interpreter keeps an ascii codec as a default (which shouldn't be the default in modern interpreters), it will choke on those lines of `setup.cfg`.

Since `setup.py` / `setup.cfg` is required to install a package from source (instead of installing with a wheel), a failure in `setup.py`'s parsing of `setup.cfg` breaks your build…

**Comment by rbarrois** [comment] 2020-08-21 07:49
Since this bug seems to be related to your CI environment, and couldn't be reproduced on our side, I'm closing this issue for now.
But please do reopen it if you've found a reliable way to reproduce it — or if new info on your side shows we could help with it!

**Closed by rbarrois** 2020-08-21 07:49 UTC
Labels: Bug, NeedInfo, Packaging
