### ISSUE TITLE
fake-factory fatal deprecation

### ISSUE THREAD

**Issue by NeveHanter** [FactoryBoy/factory_boy#333] opened 2016-12-16 16:57 UTC
`fake-factory` was fatally deprecated, and current "stable" `factory_boy` 2.7.0 on PyPI installs `fake-factory-9999.9.9` thus fails with traceback when run:
```
Traceback (most recent call last):
  File "/home/vagrant/.pycharm_helpers/pycharm/pytestrunner.py", line 60, in <module>
    main()
  File "/home/vagrant/.pycharm_helpers/pycharm/pytestrunner.py", line 34, in main
    pluginmanager=_pluginmanager, args=args)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/helpconfig.py", line 32, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 910, in pytest_cmdline_parse
    self.parse(args)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 1067, in parse
    self._preparse(args, addopts=addopts)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 1029, in _preparse
    self.pluginmanager.load_setuptools_entrypoints(entrypoint_name)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pytest_factoryboy/__init__.py", line 2, in <module>
    from .fixture import register, LazyFixture
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pytest_factoryboy/fixture.py", line 6, in <module>
    import factory
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/factory/__init__.py", line 46, in <module>
    from .faker import Faker
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/factory/faker.py", line 41, in <module>
    import faker
  File "/home/vagrant/.pyenv/versions/3.5.2/lib/python3.5/site-packages/faker/__init__.py", line 7, in <module>
    raise ImportError(error)
ImportError: The ``fake-factory`` package is now called ``Faker``.

Please update your requirements.
```

**Comment by jdufresne** [comment] 2016-12-16 17:07
Looks like this was fixed in dba31e3866cdefde1d7f37fc7f0553a12feeab9b?

**Comment by NeveHanter** [comment] 2016-12-16 17:12
Yes, but most recent PyPI version is 2.7.0 (https://pypi.python.org/pypi/factory_boy/) , and the fix is in master branch

**Comment by jeffwidman** [comment] 2016-12-16 19:35
Closing as dupe of #334 - I know this came earlier, but that one has a longer discussion

**Closed by jeffwidman** 2016-12-16 19:35 UTC
