### ISSUE TITLE
Not able to get expected datetime with FuzzyDatetime

### ISSUE THREAD

**Issue by kousiknath33** [FactoryBoy/factory_boy#384] opened 2017-05-23 09:48 UTC
I have a factory like the following:

```python
class MyFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = MyModel

    last_modified_date = FuzzyDateTime(datetime.datetime.now(tz=UTC) + timedelta(days=10),
                                       datetime.datetime.now(tz=UTC) + timedelta(days=15))
```

But when I check last_modified_date for the above instance in debugging mode, I see  its value is set to datetime.now(). I am not getting the expected datetime value.

**Comment by rbarrois** [comment] 2017-05-23 10:09
Hi,

Can you provide the related model field? If it uses ``auto_now``, Django will override any provided value whenever an instance is saved.

**Comment by kousiknath33** [comment] 2017-05-23 10:36
The model looks like following:

```
class MyModel(models.Model):
    last_modified_date = models.DateTimeField(null=True)
```

**Comment by rbarrois** [comment] 2017-05-23 11:01
This is surprising.

With your factory, calling ``MyModelFactory()`` will call ``MyModel.objects.create(last_modified_date=datetime.datetime(2017, 6, 5, 4, 13, 25, 135749)`` (or a similar random datetime).

What do you get when you run:

```python
>>> obj = MyModelFactory()
>>> obj.last_modified_date
``` ?

**Comment by kousiknath33** [comment] 2017-05-23 11:23
It is always setting the field as datetime.now().

**Comment by kousiknath33** [comment] 2017-05-23 11:25
The same logic is working for another factory. But not with this specific model.

**Comment by rbarrois** [comment] 2017-05-23 12:20
What happens when you pass in a specific datetime to the constructor, without going through the factory?

**Comment by kousiknath33** [comment] 2017-05-23 12:26
When I pass some datetime instance in the original model constructor, it creates correctly.

```
d = MyModel(last_modified_date=datetime.datetime.now( tz=UTC) + datetime.timedelta(days=25))
result: datetime.datetime(2017, 6, 17, 12, 24, 16, 72418, tzinfo=<UTC>)
```

**Comment by rbarrois** [comment] 2017-05-23 13:21
Does it also work when going through ``MyModel.objects.create()`` (the method used by factory_boy)?

If it does, I'll have to see the full factory or model.

**Comment by kousiknath33** [comment] 2017-05-23 13:52
No it doesn't work. It shows the same behaviour as the Factory.

**Comment by rbarrois** [comment] 2017-05-23 14:07
This means that the issue is somewhere within your code: either your ``create`` / ``save`` has a special behaviour, or you're using a custom ``DateTimeField``, etc.

I'm closing this issue for now; feel free to reopen it if you find a difference between ``MyModelFactory()`` and ``MyModel.objects.create(some_future_datetime)`` :)

**Closed by rbarrois** 2017-05-23 14:07 UTC
Labels: Django, NeedInfo, Q&A
